function __completions_screen_detach
	command screen -list | sed -e '1d' -e '$d' -e 's/^\t//g' -re 's/\t.*\t\(|\)/\t/g'
end

complete -c screen -s a --description 'include all capabilities (with some minor excep… [See Man Page]'
complete -c screen -s A --description 'Adapt the sizes of all windows to the size of t… [See Man Page]'
complete -c screen -s c --description 'override the default configuration file from $HOME/.'
complete -c screen -s d -s D --description 'does not start screen , but detaches the elsewh… [See Man Page]'
complete -c screen -o rd -s x -x -a "(__completions_screen_detach)"
complete -c screen -o r/-R --description '.'
complete -c screen -s r --description 'Reattach a session and if necessary detach it first.'
complete -c screen -s R --description 'Reattach a session and if necessary detach or e… [See Man Page]'
complete -c screen -o RR --description 'Reattach a session and if necessary detach or create it.'
complete -c screen -s e --description 'specifies the command character to be x and the… [See Man Page]'
complete -c screen -s f -o fn -o fa --description 'turns flow-control on, off, or automatic switching mode.'
complete -c screen -s h --description 'Specifies the history scrollback buffer to be num lines high.'
complete -c screen -s i --description 'will cause the interrupt key (usually C-c) to i… [See Man Page]'
complete -c screen -s l -o ln --description 'turns login mode on or off (for /var/run/utmp updating).'
complete -c screen -o ls --description '.'
complete -c screen -o list --description '.'
complete -c screen -o wipe --description '.'
complete -c screen -s L --description 'tells screen to turn on automatic output loggin… [See Man Page]'
complete -c screen -s m --description 'causes screen to ignore the $STY environment variable.'
complete -c screen -s O --description 'selects a more optimal output mode for your ter… [See Man Page]'
complete -c screen -s p --description 'Preselect a window.'
complete -c screen -s q --description 'Suppress printing of error messages.'
complete -c screen -s Q --description 'Some commands now can be queried from a remote … [See Man Page]'
complete -c screen -s s --description 'sets the default shell to the program specified… [See Man Page]'
complete -c screen -s S --description 'When creating a new session, this option can be… [See Man Page]'
complete -c screen -s t --description 'sets the title (a. k. a.'
complete -c screen -s T --description 'Set the $TERM environment varible using the spc… [See Man Page]'
complete -c screen -s U --description 'Run screen in UTF-8 mode.'
complete -c screen -s v --description 'Print version number.'
complete -c screen -s x --description 'Attach to a not detached screen session.  (Multi display mode).'
complete -c screen -s X --description 'Send the specified command to a running screen session.'
complete -c screen -s 4 --description 'Resolve hostnames only to IPv4 addresses.'
complete -c screen -s 6 --description 'Resolve hostnames only to IPv6 addresses.'
complete -c screen -s w --description 'screen  he can attach to the session and (per d… [See Man Page]'
complete -c screen -s k --description 'option).'
complete -c screen -s b --description 'option is given, screen will switch to the blan… [See Man Page]'
complete -c screen -s g --description 'option will show the windows inside any groups … [See Man Page]'

